### PR TITLE
Potential mitigation for issue #103 (parse exception for package name including "or")

### PR DESCRIPTION
**Pull request by JCgH4164838Gh792C124B5**
Potential mitigation for issue #103 (identifiers cannot include package names like "and" or "or"):
- Sub-optimal solution requires direct modification of OgnlParser, so if the language specification (ognl.jj, ognl.jjt) ever changes and is rebuilt using JavaCC/JJTree, the logic would have to be manually re-added.
- Mitigation only works for sub-package names, still fails for patterns like "or.something".

### CODE REVIEW

**Comment by JCgH4164838Gh792C124B5** [comment]
Hello OGNL Team.

This PR may not be desirable, given it has to change `OgnlParser` directly, and there may be unanticipated side-effects from the change as well.  It should be reviewed thoroughly before considering using it.

The changes pass the unit tests, and passed a Struts 2.5.27-SNAPSHOT regression build using an OGNL snapshot built from the PR code, but further testing and consideration may be needed (for example, something with many complex OGNL expressions).

If someone familiar with JavaCC/JJTree could review what the `OgnlParser` changes are attempting to do, and propose a way to change the language specification files (`ognl.jj`, `ognl.jjt`) to achieve the same (or better) result, that would be great.

**Comment by lukaszlenart** [comment]
Thanks a lot for this PR, yet I have a question about `or.package` or `and.package` - what's the main issue to recognise such expressions? Isn't just a matter of checking if `.` follows the package name?

**Comment by JCgH4164838Gh792C124B5** [comment]
Hi @lukaszlenart .

The main issue appears to be that when the OGNL language parser encounters the patterns that match a token name (of which "and" or "or" are only two of many), it interprets them as tokens, even if they are part of a package name.

My attempts to figure out how the JavaCC/JJTree language specification might be changed to differentiate between package "xxx.and.yyy and an expression "x and y" fell short, so I resorted to tracing breakpoints in the generated code to see if the state machine flow could be "safely altered" to have the desired result. 

I still dislike the solution I came up with, since it deviates from the JavaCC/JJTree language specification.  I think it is too risky to actually use this PR's solution, but was hoping a JavaCC/JJTree expert might see it, and be able to propose a proper fix.

Without a proper fix / solution, it might be better to simply document the limitation that OGNL cannot process any package names whose components exactly match OGNL token names.

**Comment by lukaszlenart** [comment]
I'm not a JavaCC/JJTree expert, I would like to understand how does it work but this is really out of my skills :) That being said and taking your doubts into account I would just left this PR open hoping someone will come up with a better solution and document OGNL limitations.

**Comment by lukaszlenart** [comment]
I added a note about those limitations https://github.com/jkuhnert/ognl/pull/135

**Pull request closed without merging**
