### PR TITLE
Turns OgnlContext into independent class not inherited from Map

### PR DESCRIPTION
**Pull request by lukaszlenart**

### CODE REVIEW

**Comment by jstenzel** [comment]
What replaces the constructor Ognl.getValue, which I used to be able to simply pass a map to, or how do I get from the simple map to the OgnlContext now?

**Comment by lukaszlenart** [comment]
Create an instance of `OgnlContext` and use `setValues()` - I can always add some helper method if you want to, like `OgnlContext.of(Map)`?

**Comment by jstenzel** [comment]
Helper methods are always helpful, but your info is enough for now. Many thanks

**Comment by lukaszlenart** [comment]
I add a small helper #220

**Pull request merged**
